# Site settings
title: BanhmiDev
description: >-
  Hi, my name is Son Nguyen and I'm a software developer based in Germany.
lang: en-US # default lang
timezone: Europe/Berlin
mode: dark

# Profile settings
author:
  name: Son Nguyen
  bio: >
    Hi, my name is Son Nguyen and I'm a software developer based in Germany.<br/><br/>
    Besides the boring stuff, I've been dabbling in game development and hope to be able to publish my first game soon.<br/><br/>

    For security matters, you can find my Public GPG Key <a href="/assets/banhmidev.asc">here</a>.
  username: BanhmiDev
  twitter: BanhmiDev
  avatar: /assets/img/avatar.png

# URL settings
url: "https://banhmi.dev"
baseurl:
permalink: /:title/

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
